name: Kids Video Bot â€“ Generate & Download

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install system dependencies
      run: |
       sudo apt-get update
       sudo apt-get install -y ffmpeg imagemagick
       sudo sed -i 's/none/read,write/g' /etc/ImageMagick-6/policy.xml

  
  
    - name: Install Python libraries
      run: python -m pip install moviepy pillow gtts numpy scipy
      
    - name: Debug moviepy install
      run: |
        python - <<EOF
        import moviepy
        print("moviepy version:", moviepy.__version__)
        from moviepy import VideoFileClip
        print("moviepy import OK")
        EOF
        
    - name: Generate story
      env:
         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: ${{ secrets.HF_API_TOKEN }}
         run: python scripts/generate_story.py     
    - name: Debug HF token presence
      run: |
       if [ -z "$HF_API_TOKEN" ]; then
       echo "HF_API_TOKEN is NOT set"
       else
       echo "HF_API_TOKEN is set"
       fi
    - name: Create background video
      run: python scripts/create_background_video.py

    - name: Create background music
      run: python scripts/create_background_music.py

    - name: Generate voice
      run: python scripts/generate_voice.py

    - name: Generate images
      run: python scripts/generate_images.py

    - name: Debug output files
      run: ls -lh output
       
    - name: Create video
      run: python scripts/create_video.py

    - name: Upload output as artifact
      uses: actions/upload-artifact@v4
      with:
        name: kids-video-output
        path: output/
