name: Kids Video Bot â€“ Generate & Download

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install system dependencies
      run: |
       sudo apt-get update
       sudo apt-get install -y ffmpeg

    - name: Install Python libraries
      run: |
       pip install pillow piper-tts
      
  
  
    - name: Install Python libraries
      run: pip install pillow

    - name: Generate story
      run: python scripts/generate_story.py

    - name: Generate voice
      run: python scripts/generate_voice.py

    - name: Generate images
      run: python scripts/generate_images.py

    - name: Debug output files
      run: ls -lh output
       
    - name: Create video
      run: python scripts/create_video.py

    - name: Upload output as artifact
      uses: actions/upload-artifact@v4
      with:
        name: kids-video-output
        path: output/
